// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwevkynljkyjdaqxqebr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3ZXZreW5samt5amRhcXhxZWJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMjk1OTcsImV4cCI6MjA2NDcwNTU5N30.0zYQfw4rGo-f7q6yyNnrsCQ9qFigkSLMh4P_i01MPps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);